steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/aryeelab/cas-designer:$SHORT_SHA', '-t', 'gcr.io/aryeelab/cas-designer:latest', '--build-arg', 'VERSION=$SHORT_SHA', '.']

images: 
- 'gcr.io/aryeelab/cas-designer'

timeout: 3600s
